version: 0.0
os: linux
files:
   - source: /index.html
     destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 6000
      runas: root
    - location: scripts/start_server
      timeout: 6000
      runas: root
 
  AfterInstall:
    - location: scripts/restart.sh
      timeout: 6000
      runas: root


  

